version: '3'
services:
  app:
    build:
      context: .
      args:
        RAILS_ENV: ${RAILS_ENV:-development}
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'

  muffet:
    depends_on:
      - app
    image: raviqqe/muffet
    entrypoint:
      - ash
      - -c

  ruby:
    image: ruby:2.7.5-slim-buster
    working_dir: /app
    volumes:
      - '.:/app'
