version: '3'
services:
  app:
    build:
      context: .
      args:
        RAILS_ENV: ${RAILS_ENV:-development}
        RENDER_PR_APP: test
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
