version: '3'
services:
  app:
    build:
      context: .
      args:
        RAILS_ENV: production
        RENDER_PR_APP: false
    ports:
      - '3000:3000'
    environment:
      - "SECRET_KEY_BASE=xxx"
