steps:
  - wait

  # If the user *isn't* in the deploy team, require a block step for manual
  # verification by someone who is in the team.
  - block: ":rocket: Deploy"
    key: "deploy-check-block"
    if: "!(build.creator.teams includes 'deploy') && build.branch == 'main'"

  - name: ":docker::ecr: Push to ECR"
    key: "ecr-push"
    command: ".buildkite/push-image.sh"
    depends_on: "deploy-check-block"
    if: "build.branch == 'main'"
    agents:
      queue: deploy
    plugins:
      ecr#v2.0.0:
        login: true
        account-ids: ${ECR_ACCOUNT_ID}

  - label: ":docker::rocket:"
    key: deploy
    branches: main
    depends_on: ecr-push
    concurrency: 1
    concurrency_group: docs-deploy
    agents:
      queue: deploy
    command: scripts/deploy-ecs

  # Refresh the search index after a deployment
  - label: "🔎🪄"
    trigger: docs-algolia-crawler
    async: true
    depends_on: deploy
